Repository guardian/frontend, pull requests merged in 2018-05, with the labels that each got.

#19588 Set up Xaxis bidder using AppNexus adapter
  static/src/javascripts/projects/commercial/modules/prebid/bidder-config.js
  static/src/javascripts/projects/commercial/modules/prebid/labels.js
  static/src/javascripts/projects/commercial/modules/prebid/prebid.js
  static/src/javascripts/projects/commercial/modules/prebid/types.js
Labels: Commercial: Programmatic

#19583 add LineHeightFontSize server-side test
  common/app/experiments/Experiments.scala
  common/app/templates/inlineJS/blocking/applyRenderConditions.scala.js
  static/src/stylesheets/module/content-garnett/_types.scss
Labels: commercial

#19609 Add Xaxis to Prebid auctions
  package.json
  static/src/javascripts/projects/commercial/modules/prebid/bidder-config.js
  static/src/javascripts/projects/commercial/modules/prebid/prebid.js
  yarn.lock
Labels: Commercial: Programmatic

#19622 Bump audience (0%👉30%) for the sign in engagement alert AB test
  static/src/javascripts/projects/common/modules/experiments/tests/sign-in-engagement-banner-display.js
Labels: Do not merge ⚠️

#19638 Tab-able account menu
  common/app/views/fragments/nav/userAccountDropdown.scala.html
Labels: a11y

#19644 Make video play button expand on focus
  common/app/views/fragments/atoms/youtube.scala.html
  static/src/javascripts/projects/common/modules/atoms/youtube.js
  static/src/stylesheets/module/content-garnett/_media-player.scss
Labels: a11y

#19651 Video carousel keyboard and screen reader improvements
  common/app/views/fragments/atoms/youtube.scala.html
  common/app/views/fragments/containers/facia_cards/videoContainer.scala.html
  static/src/javascripts/projects/common/modules/video/video-container.js
  static/src/stylesheets/module/facia-garnett/_container--video.scss
  static/src/stylesheets/module/facia/_container--video.scss
Labels: a11y

#19648 Close 'More', 'Edition Picker' and 'Account' menus with ESC key press
  static/src/javascripts/projects/common/modules/navigation/new-header.js
  static/src/stylesheets/layout/nav/_main-menu-toggle.scss
Labels: a11y

#19707 Support multiple sizes in Prebid Index Exchange bids
  static/src/javascripts/projects/commercial/modules/prebid/bid-config.js
  static/src/javascripts/projects/commercial/modules/prebid/prebid.js
Labels: Commercial: Programmatic

#19769 AB test for the blocking cookie banner
  common/app/conf/switches/ABTestSwitches.scala
  static/src/javascripts/projects/common/modules/experiments/ab-tests.js
  static/src/javascripts/projects/common/modules/experiments/tests/first-pv-consent-blocker.js
  static/src/javascripts/projects/common/modules/ui/first-pv-consent-banner.js
  static/src/javascripts/projects/common/modules/ui/first-pv-consent-banner.spec.js
  static/src/stylesheets/module/_release-message.scss
Labels: Do not merge ⚠️, Work in progress 🏗
