Repository guardian/frontend, pull requests merged in 2018-12, with the labels that each got.

#20678 sign the image urls
  commercial/app/model/capi/CapiImages.scala
  common/app/layout/WidthsByBreakpoint.scala
  common/app/model/dotcomrendering/pageElements/PageElement.scala
  common/app/views/fragments/image.scala.html
  common/app/views/fragments/items/elements/facia_cards/image.scala.html
  common/app/views/support/ImageProfile.scala
Labels: dotcomrendering

#20788 Better landmarks on fronts
  common/app/views/fragments/commercial/containerWrapper.scala.html
  common/app/views/fragments/containers/facia_cards/containerHeader.scala.html
  common/app/views/fragments/containers/facia_cards/standardHeaderMeta.scala.html
  common/app/views/fragments/items/elements/facia_cards/itemHeader.scala.html
  common/app/views/fragments/items/elements/facia_cards/sublink.scala.html
  common/app/views/fragments/items/facia_cards/meta.scala.html
  facia/app/views/fragments/frontBody.scala.html
  static/src/stylesheets/inline/story-package-garnett.scss
  static/src/stylesheets/module/facia-garnett/_container.scss
Labels: a11y

#20810 Provide visual indication of focus when using keyboard navigation
  static/src/stylesheets/module/commercial/paidfor/_paidfor-band.scss
Labels: accessibility

#20832 Improve tab order for edition picker
  common/app/views/fragments/header.scala.html
  static/src/stylesheets/layout/nav/_edition-picker-toggle.scss
Labels: accessibility

#20826 ⚡️📢☁️( Adds elements and logic to separate soundcloud embeds from embeds*)
  common/app/model/dotcomrendering/pageElements/PageElement.scala
  common/app/views/support/cleaner/AmpEmbedCleaner.scala
  common/app/views/support/cleaner/AmpSoundcloud.scala
Labels: dotcomrendering
