Repository guardian/frontend, pull requests merged in 2021-09, with the labels that each got.

#24135 FIX: `top-above-nav` flex styling
  static/src/stylesheets/module/_adslot.scss
Labels: bug, commercial

#24136 Do not reserve space for `top-above-nav` on mobile
  static/src/stylesheets/module/_adslot.scss
Labels: bug, commercial

#24132 Remove qwery from spacefinder
  static/src/javascripts/projects/common/modules/spacefinder.js
Labels: commercial

#24128 Remove qwery from component
  static/src/javascripts/projects/common/modules/component.js
  static/src/javascripts/projects/common/modules/component.spec.js
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: commercial

#24050 convert `$` to native JS
  static/src/javascripts/projects/commercial/adblock-ask.spec.ts
  static/src/javascripts/projects/commercial/adblock-ask.ts
Labels: commercial

#24148 Convert page-skin to TS
  static/src/javascripts.flow.archive/projects/commercial/modules/creatives/page-skin.js
  static/src/javascripts/projects/commercial/modules/creatives/page-skin.js
  static/src/javascripts/projects/commercial/modules/creatives/page-skin.ts
  static/src/javascripts/types/global.d.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24150 Refresh blocked ads (Confiant)
  common/app/conf/switches/ABTestSwitches.scala
  static/src/javascripts.flow.archive/projects/commercial/modules/ad-verification/prepare-ad-verification.js
  static/src/javascripts/lib/noop.js
  static/src/javascripts/lib/noop.ts
  static/src/javascripts/projects/commercial/modules/ad-verification/prepare-ad-verification.js
  static/src/javascripts/projects/commercial/modules/ad-verification/prepare-ad-verification.spec.ts
  static/src/javascripts/projects/commercial/modules/ad-verification/prepare-ad-verification.ts
  static/src/javascripts/projects/common/modules/experiments/ab-tests.ts
  static/src/javascripts/projects/common/modules/experiments/tests/refresh-confiant-blocked-ads.ts
  static/src/javascripts/types/global.d.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: commercial, TypeScript

#24176 Always add Confiant targeting
  static/src/javascripts/projects/commercial/modules/ad-verification/prepare-ad-verification.spec.ts
  static/src/javascripts/projects/commercial/modules/ad-verification/prepare-ad-verification.ts
Labels: commercial

#24170 Stop sending metrics for `improvedigital`
  static/src/javascripts/projects/commercial/modules/header-bidding/prebid/prebid.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: commercial

#24187 Only set ad Manager Group if consented
  static/src/javascripts/projects/common/modules/commercial/build-page-targeting.js
  static/src/javascripts/projects/common/modules/commercial/build-page-targeting.spec.js
Labels: commercial

#24202 Convert `empty-advert` to TypeScript
  static/src/javascripts.flow.archive/projects/commercial/modules/dfp/empty-advert.js
  static/src/javascripts/projects/commercial/modules/dfp/empty-advert.js
  static/src/javascripts/projects/commercial/modules/dfp/empty-advert.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24200 Convert `add-slot` to TypeScript
  static/src/javascripts.flow.archive/projects/commercial/modules/dfp/add-slot.js
  static/src/javascripts/projects/commercial/modules/comment-adverts.ts
  static/src/javascripts/projects/commercial/modules/dfp/add-slot.js
  static/src/javascripts/projects/commercial/modules/dfp/add-slot.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24198 Convert `display-ads` to TypeScript
  static/src/javascripts.flow.archive/projects/commercial/modules/dfp/display-ads.js
  static/src/javascripts/projects/commercial/modules/dfp/display-ads.js
  static/src/javascripts/projects/commercial/modules/dfp/display-ads.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24195 Convert `wait-for-advert` to TypeScript
  static/src/javascripts.flow.archive/projects/commercial/modules/dfp/wait-for-advert.js
  static/src/javascripts/projects/commercial/modules/dfp/wait-for-advert.js
  static/src/javascripts/projects/commercial/modules/dfp/wait-for-advert.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24197 Convert `queue-advert` to TypeScript
  static/src/javascripts.flow.archive/projects/commercial/modules/dfp/queue-advert.js
  static/src/javascripts/projects/commercial/modules/dfp/queue-advert.js
  static/src/javascripts/projects/commercial/modules/dfp/queue-advert.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24211 Convert FiniteStateMachine to TypeScript
  static/src/javascripts.flow.archive/lib/fsm.js
  static/src/javascripts/lib/fsm.js
  static/src/javascripts/lib/fsm.ts
  static/src/javascripts/projects/commercial/modules/hosted/gallery.js
  static/src/javascripts/projects/common/modules/gallery/lightbox.js
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24201 Convert `fill-advert-slots` to TypeScript
  static/src/javascripts.flow.archive/projects/commercial/modules/dfp/fill-advert-slots.js
  static/src/javascripts/projects/commercial/modules/dfp/fill-advert-slots.js
  static/src/javascripts/projects/commercial/modules/dfp/fill-advert-slots.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24199 Convert `display-lazy-ads` to TypeScript
  static/src/javascripts.flow.archive/projects/commercial/modules/dfp/display-lazy-ads.js
  static/src/javascripts/lib/partition.spec.ts
  static/src/javascripts/lib/partition.ts
  static/src/javascripts/projects/commercial/modules/dfp/display-lazy-ads.js
  static/src/javascripts/projects/commercial/modules/dfp/display-lazy-ads.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24234 Serve the standalone commercial bundle to 51%
  common/app/experiments/Experiments.scala
  docs/05-commercial/03-commercial-javascript.md
  docs/README.md
Labels: commercial, Do not merge ⚠️
