Repository guardian/frontend, pull requests merged in 2021-12, with the labels that each got.

#24460 Fix type of DFP non-refreshable line items
  static/src/javascripts/projects/commercial/modules/dfp/on-slot-render.ts
  static/src/javascripts/types/global.d.ts
Labels: bug, TypeScript

#24442 Convert set-ad-test-cookie to TypeScript
  static/src/javascripts/projects/commercial/modules/set-adtest-cookie.js
  static/src/javascripts/projects/commercial/modules/set-adtest-cookie.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24461 Remove type assertions from `prepare-googletag`
  static/src/javascripts.flow.archive/projects/commercial/modules/dfp/prepare-googletag.js
  static/src/javascripts/projects/commercial/modules/dfp/prepare-googletag.ts
Labels: commercial, Commercial: Programmatic, TypeScript

#24466 Use `getCookie` from @guardian/libs in Identity API
  static/src/javascripts/projects/common/modules/identity/api.spec.js
  static/src/javascripts/projects/common/modules/identity/api.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24468 Prettier + ESLint on JavaScript
  static/src/javascripts/lib/__mocks__/config.js
  static/src/javascripts/lib/__mocks__/fastdom-promise.js
  static/src/javascripts/lib/__mocks__/fastdom.js
  static/src/javascripts/lib/__mocks__/mediator.js
  static/src/javascripts/lib/__mocks__/raven.js
  static/src/javascripts/lib/array-utils.js
  static/src/javascripts/lib/comready.js
  static/src/javascripts/lib/config.js
  static/src/javascripts/lib/config.spec.js
  static/src/javascripts/lib/cookies.js
  static/src/javascripts/lib/cookies.spec.js
  static/src/javascripts/lib/defer-to-analytics.js
  static/src/javascripts/lib/detect.js
  static/src/javascripts/lib/getPrivacyFramework.js
  static/src/javascripts/lib/raven.js
  static/src/javascripts/lib/report-error.js
  static/src/javascripts/lib/robust.js
  static/src/javascripts/lib/user-timing.spec.js
  static/src/javascripts/lib/window-performance.js
  static/src/javascripts/projects/commercial/modules/dfp/prepare-a9.js
  static/src/javascripts/projects/commercial/modules/dfp/prepare-a9.spec.js
  static/src/javascripts/projects/commercial/modules/dfp/prepare-permutive.js
  static/src/javascripts/projects/commercial/modules/dfp/prepare-permutive.spec.js
  static/src/javascripts/projects/commercial/modules/dfp/redplanet.js
  static/src/javascripts/projects/commercial/modules/dfp/redplanet.spec.js
  static/src/javascripts/projects/commercial/modules/hosted/gallery.js
  static/src/javascripts/projects/common/modules/analytics/mvt-cookie.js
  static/src/javascripts/projects/common/modules/article/space-filler.js
  static/src/javascripts/projects/common/modules/commercial/acquisitions-link-enrichment.js
  static/src/javascripts/projects/common/modules/commercial/contributions-service.js
  static/src/javascripts/projects/common/modules/commercial/contributions-utilities.js
  static/src/javascripts/projects/common/modules/commercial/support-utilities.js
  static/src/javascripts/projects/common/modules/experiments/tests/sign-in-gate-main-control.js
  static/src/javascripts/projects/common/modules/experiments/tests/sign-in-gate-main-variant.js
  static/src/javascripts/projects/common/modules/identity/auth-component-event-params.js
  static/src/javascripts/projects/common/modules/onward/geo-most-popular.js
  static/src/javascripts/projects/common/modules/spacefinder.js
  static/src/javascripts/projects/common/modules/ui/cmp-ui.js
  static/src/javascripts/projects/common/modules/ui/sticky.js
Labels: ready-to-deploy

#24465 Convert `mvt-cookie` to TypeScript
  static/src/javascripts.flow.archive/projects/common/modules/analytics/__mocks__/mvt-cookie.js
  static/src/javascripts.flow.archive/projects/common/modules/analytics/mvt-cookie.js
  static/src/javascripts/projects/common/modules/analytics/__mocks__/mvt-cookie.js
  static/src/javascripts/projects/common/modules/analytics/mvt-cookie.js
  static/src/javascripts/projects/common/modules/analytics/mvt-cookie.ts
  static/src/javascripts/projects/common/modules/experiments/ab-core.spec.js
  static/src/javascripts/projects/common/modules/experiments/ab-core.ts
  static/src/javascripts/projects/common/modules/experiments/ab.spec.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: TypeScript

#24488 Non-refreshable line item experiment participation to 20%
  common/app/experiments/Experiments.scala
Labels: commercial
