Repository guardian/frontend, pull requests merged in 2021-03, with the labels that each got.

#23599 Remove reqwest
  dev/nodeFetch.js
  docs/02-architecture/03-libraries-we-use.md
  package.json
  static/src/javascripts/bootstraps/enhanced/newsletters.js
  static/src/javascripts/lib/ajax.js
  static/src/javascripts/lib/ajax.spec.js
  static/src/javascripts/lib/fetch-json.js
  static/src/javascripts/lib/fetch-json.spec.js
  static/src/javascripts/lib/fetch.js
  static/src/javascripts/lib/fetch.spec.js
  static/src/javascripts/projects/common/modules/analytics/beacon.js
  static/src/javascripts/projects/common/modules/gallery/lightbox.js
  static/src/javascripts/projects/common/modules/identity/api.js
  static/src/javascripts/projects/common/modules/identity/api.spec.js
  static/src/javascripts/projects/common/modules/identity/consents.js
  static/src/javascripts/projects/common/modules/identity/upsell/account-creation/AccountCreationForm.js
  static/src/javascripts/projects/common/modules/video/metadata.js
  static/src/javascripts/projects/facia/modules/ui/snaps.js
  static/src/javascripts/projects/journalism/modules/submit-form.js
  yarn.lock
Labels: dependencies, performance, requires testing

#23629 Fix `ajax.js` error
  static/src/javascripts/lib/ajax.js
Labels: bug

#23644 Typescript discussion api
  static/src/javascripts/projects/common/modules/discussion/api.js
  static/src/javascripts/projects/common/modules/discussion/api.ts
  static/src/javascripts/projects/common/modules/discussion/comment-box.spec.js
Labels: TypeScript

#23613 Fix top banner ad label layout shift
  common/app/views/fragments/commercial/topBanner.scala.html
  static/src/javascripts/bootstraps/commercial.dcr.js
  static/src/javascripts/bootstraps/commercial.js
  static/src/javascripts/projects/commercial/modules/close-disabled-slots.js
  static/src/javascripts/projects/commercial/modules/dfp/fill-advert-slots.js
  static/src/javascripts/projects/commercial/modules/dfp/prepare-googletag.js
  static/src/javascripts/projects/commercial/modules/dfp/render-advert-label.js
  static/src/javascripts/projects/commercial/modules/dfp/render-advert-label.spec.js
  static/src/javascripts/projects/commercial/modules/dfp/render-advert-label.ts
  static/src/javascripts/projects/commercial/modules/remove-slots.spec.js
  static/src/javascripts/projects/commercial/modules/remove-slots.ts
  static/src/javascripts/types/global.d.ts
  static/src/stylesheets/module/_adslot.scss
Labels: TypeScript, commercial
