Repository guardian/frontend, pull requests merged in 2021-01, with the labels that each got.

#23419 Labs logo contrast
  common/app/views/fragments/items/facia_cards/paidContentCard.scala.html
Labels: bug, commercial

#23415 Use idapi for email embeds
  applications/app/AppLoader.scala
  common/app/common/configuration.scala
  common/app/controllers/EmailSignupController.scala
  common/app/services/newsletters/EmailEmbedAgent.scala
  common/app/services/newsletters/EmailEmbedLifecycle.scala
  common/app/services/newsletters/NewsletterApi.scala
  common/app/views/emailFragment.scala.html
  common/app/views/emailSubscriptionSuccessResult.scala.html
  common/app/views/fragments/email/signup/result/emailResultNewDesign.scala.html
  common/app/views/fragments/email/signup/subscription/emailSignUpNewDesign.scala.html
  dev-build/app/AppLoader.scala
  identity/app/AppLoader.scala
  identity/app/services/IdentityServices.scala
  preview/app/AppLoader.scala
Labels: Do not merge ⚠️

#23263 docs: Fix typos and dead links
  docs/99-archives/crepes.md
Labels: lang="fr"

#23473 Remove Lotame
  common/app/conf/switches/CommercialSwitches.scala
  common/app/views/fragments/inlineJSNonBlocking.scala.html
  docs/02-architecture/06-client-side-architecture.md
  static/src/javascripts/projects/commercial/modules/header-bidding/prebid/appnexus.js
  static/src/javascripts/projects/commercial/modules/header-bidding/prebid/appnexus.spec.js
  static/src/javascripts/projects/commercial/modules/header-bidding/prebid/bid-config.js
  static/src/javascripts/projects/commercial/modules/third-party-tags.js
  static/src/javascripts/projects/commercial/modules/third-party-tags.spec.js
Labels: commercial

#23291 Remote liveblog epics
  static/src/javascripts/projects/common/modules/commercial/contributions-liveblog-utilities.js
  static/src/javascripts/projects/common/modules/commercial/contributions-service.js
  static/src/javascripts/projects/common/modules/experiments/ab.js
Labels: Do not merge ⚠️
