Repository guardian/frontend, pull requests merged in 2021-04, with the labels that each got.

#23655 Reinstate “Typescript discussion api”
  static/src/javascripts/projects/common/modules/discussion/api.js
  static/src/javascripts/projects/common/modules/discussion/api.ts
  static/src/javascripts/projects/common/modules/discussion/comment-box.spec.js
Labels: TypeScript

#23385 Use block dateTimes rather than article for Blocks
  common/app/model/dotcomrendering/DotcomRenderingSupportTypes.scala
  common/app/model/dotcomrendering/DotcomRenderingUtils.scala
Labels: Do not merge ⚠️

#23650 Typescript avatar api
  static/src/javascripts/projects/common/modules/avatar/api.js
  static/src/javascripts/projects/common/modules/avatar/api.ts
Labels: TypeScript

#23687 Convert identity API to Typescript
  static/src/javascripts/bootstraps/standard/main.js
  static/src/javascripts/projects/common/modules/avatar/api.ts
  static/src/javascripts/projects/common/modules/discussion/api.ts
  static/src/javascripts/projects/common/modules/identity/api.js
  static/src/javascripts/projects/common/modules/identity/api.spec.js
  static/src/javascripts/projects/common/modules/identity/api.ts
  static/src/javascripts/types/global.d.ts
Labels: TypeScript

#23614 Convert `fetch-json` to Typescript
  static/src/javascripts/bootstraps/enhanced/football.js
  static/src/javascripts/bootstraps/standard/main.js
  static/src/javascripts/lib/fetch-json.js
  static/src/javascripts/lib/fetch-json.spec.js
  static/src/javascripts/lib/fetch-json.ts
  static/src/javascripts/lib/geolocation.js
  static/src/javascripts/projects/admin/bootstraps/radiator.js
  static/src/javascripts/projects/commercial/modules/hosted/next-video.js
  static/src/javascripts/projects/commercial/modules/hosted/next-video.spec.js
  static/src/javascripts/projects/commercial/modules/hosted/onward.js
  static/src/javascripts/projects/commercial/modules/hosted/onward.spec.js
  static/src/javascripts/projects/common/modules/article/membership-events.js
  static/src/javascripts/projects/common/modules/article/rich-links.js
  static/src/javascripts/projects/common/modules/atoms/youtube.js
  static/src/javascripts/projects/common/modules/business/stocks.js
  static/src/javascripts/projects/common/modules/commercial/contributions-service.js
  static/src/javascripts/projects/common/modules/commercial/user-features.js
  static/src/javascripts/projects/common/modules/commercial/user-features.spec.js
  static/src/javascripts/projects/common/modules/component.js
  static/src/javascripts/projects/common/modules/component.spec.js
  static/src/javascripts/projects/common/modules/discussion/comment-count.js
  static/src/javascripts/projects/common/modules/discussion/comment-count.spec.js
  static/src/javascripts/projects/common/modules/discussion/comments.js
  static/src/javascripts/projects/common/modules/discussion/loader.js
  static/src/javascripts/projects/common/modules/discussion/whole-discussion.js
  static/src/javascripts/projects/common/modules/identity/api.spec.js
  static/src/javascripts/projects/common/modules/identity/api.ts
  static/src/javascripts/projects/common/modules/identity/upsell/account-creation/AccountCreationForm.js
  static/src/javascripts/projects/common/modules/onward/breaking-news.js
  static/src/javascripts/projects/common/modules/onward/breaking-news.spec.js
  static/src/javascripts/projects/common/modules/onward/related.js
  static/src/javascripts/projects/common/modules/social/share-count.js
  static/src/javascripts/projects/common/modules/sport/football/match-info.js
  static/src/javascripts/projects/common/modules/sport/football/tag-page-stats.js
  static/src/javascripts/projects/common/modules/ui/autoupdate.js
  static/src/javascripts/projects/common/modules/video/metadata.js
  static/src/javascripts/projects/facia/modules/onwards/search-tool.js
  static/src/javascripts/projects/facia/modules/onwards/search-tool.spec.js
  static/src/javascripts/projects/facia/modules/onwards/weather.js
  static/src/javascripts/projects/facia/modules/onwards/weather.spec.js
  static/src/javascripts/projects/facia/modules/ui/container-show-more.js
  static/src/javascripts/projects/facia/modules/ui/live-blog-updates.js
Labels: TypeScript

#23693 Fix: no empty URL in `fetch-json` for fully qualified resource
  static/src/javascripts/lib/fetch-json.spec.js
  static/src/javascripts/lib/fetch-json.ts
Labels: bug

#23696 Fix avatar API promise
  static/src/javascripts/projects/common/modules/discussion/user-avatars.js
Labels: bug

#23697 Do not include credentials in `fetch-json` on path-absolute-URL strings
  static/src/javascripts/lib/fetch-json.ts
Labels: bug

#23741 Remove qwery from fill-advert-slots.js
  static/src/javascripts/projects/commercial/modules/dfp/fill-advert-slots.js
Labels: ready-to-deploy

#23745 Remove qwery from commercial hosted onward journey carousel
  static/src/javascripts.flow.archive/projects/commercial/modules/hosted/onward-journey-carousel.js
  static/src/javascripts.flow.archive/projects/commercial/modules/hosted/onward-journey-carousel.spec.js
  static/src/javascripts/projects/commercial/modules/hosted/about.spec.js
  static/src/javascripts/projects/commercial/modules/hosted/gallery.spec.js
  static/src/javascripts/projects/commercial/modules/hosted/onward-journey-carousel.js
  static/src/javascripts/projects/commercial/modules/hosted/onward-journey-carousel.spec.js
  static/src/javascripts/projects/commercial/modules/hosted/onward-journey-carousel.ts
Labels: TypeScript, commercial

#23752 Add Ozone bidders to Prebid.js analytics
  package.json
  yarn.lock
Labels: commercial

#23744 Remove qwery from paid-containers.js
  static/src/javascripts.flow.archive/projects/commercial/modules/paid-containers.js
  static/src/javascripts/projects/commercial/modules/paid-containers.js
  static/src/javascripts/projects/commercial/modules/paid-containers.ts
Labels: TypeScript, commercial
