Repository guardian/frontend, pull requests merged in 2022-11, with the labels that each got.

#25641 Add “World Cup 2022” to the Football nav
  common/app/navigation/NavLinks.scala
  common/test/resources/reference-navigation.json
Labels: football

#25507 GitHub Workflows security hardening
  .github/workflows/snyk.yml
  .github/workflows/typescript.yml
Labels: Health, Stale

#25642 Bump commercial-shared to 6.1.7
  project/Dependencies.scala
Labels: commercial

#25634 Align header Logo with DCR
  common/app/views/fragments/header.scala.html
  static/src/stylesheets/layout/nav/_new-header.scss
Labels: Health

#25647 replace dual 'Contribute' and 'Subscribe' CTAs with single 'Support' CTA
  common/app/views/fragments/footer.scala.html
Labels: Do not merge ⚠️

#25629 Skip header bidding in Canada
  common/app/conf/switches/ABTestSwitches.scala
  static/src/javascripts/projects/commercial/modules/dfp/prepare-a9.spec.ts
  static/src/javascripts/projects/commercial/modules/dfp/prepare-a9.ts
  static/src/javascripts/projects/commercial/modules/dfp/prepare-prebid.spec.ts
  static/src/javascripts/projects/commercial/modules/dfp/prepare-prebid.ts
  static/src/javascripts/projects/common/modules/analytics/shouldCaptureMetrics.ts
  static/src/javascripts/projects/common/modules/experiments/ab-tests.ts
  static/src/javascripts/projects/common/modules/experiments/tests/removePrebidA9Canada.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: commercial, Work in progress 🏗

#25664 Consentless fluid ads
  static/src/javascripts/bootstraps/standalone.commercial.ts
  static/src/javascripts/projects/commercial/modules/consentless/define-slot.ts
  static/src/javascripts/projects/commercial/modules/consentless/init-safeframes.ts
  static/src/javascripts/projects/commercial/modules/consentless/prepare-ootag.ts
  static/src/javascripts/types/global.d.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: commercial

#25671 Tidy consentless fluid handling
  static/src/javascripts/projects/commercial/modules/consentless/prepare-ootag.ts
Labels: commercial

#25675 feat: add Football World Cup 2022 badge
  common/app/model/Badges.scala
  static/public/images/badges/world-cup-2022.svg
Labels: Do not merge ⚠️

#25694 Fix world cup 2022 US sponsorship logo
  commercial/app/model/capi/Lookup.scala
  data/database/5a3468438bb02ded9dcd57c3ddedffd23b77089742c166464c5cd0b1ef319e40
  data/database/d657dcf21eea76683e284329d4f556647680015870afced2db181983865edf5d
Labels: commercial

#25682 Proposal: Dynamically import the consentless scripts
  static/src/javascripts/bootstraps/commercial.consentless.ts
  static/src/javascripts/bootstraps/standalone.commercial.ts
  tools/__tasks__/commercial/graph/output/standalone.commercial.ts.json
Labels: commercial

#25678 Add slot-level targeting to Opt Out
  static/src/javascripts/projects/commercial/modules/consentless/define-slot.ts
  static/src/javascripts/projects/commercial/modules/consentless/dynamic/article-inline.ts
  static/src/javascripts/projects/commercial/modules/consentless/dynamic/liveblog-inline.ts
  static/src/javascripts/projects/commercial/modules/consentless/init-fixed-slots.ts
  static/src/javascripts/types/global.d.ts
Labels: commercial

#25725 Setup empty test for billboards in merchandising slots
  common/app/experiments/Experiments.scala
Labels: commercial
