Repository guardian/frontend, pull requests merged in 2023-03, with the labels that each got.

#25809 Percy Visual Regression Testing
  .github/workflows/commercial-e2e-visual.yml
  cypress/fixtures/api/long-read.ts
  cypress/lib/rewriteGamRequest.ts
  cypress/lib/stubApiRequests.ts
  cypress/lib/util.ts
  cypress/snapshot/snapshot-article-long-read.cy.ts
  cypress/snapshot/snapshot-article-standard.cy.ts
  cypress/snapshot/snapshot-standard-article.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package.json
  yarn.lock
Labels: Work in progress 🏗

#25958 Bump commercial-bundle to `1.4.1` and commercial-core to `5.4.4`
  package.json
  yarn.lock
Labels: commercial

#25950 Switch Left and Right in Eithers
  applications/app/controllers/AtomPageController.scala
  applications/app/controllers/EmbedController.scala
  applications/app/controllers/GalleryController.scala
  applications/app/controllers/ImageContentController.scala
  applications/app/controllers/InteractiveController.scala
  applications/app/controllers/MediaController.scala
  applications/app/controllers/QuizController.scala
  applications/app/services/ImageQuery.scala
  article/app/controllers/ArticleController.scala
  article/app/controllers/LiveBlogController.scala
  article/app/model/LiveBlogHelpers.scala
  common/app/common/ModelOrResult.scala
  common/app/common/package.scala
  common/app/controllers/IndexControllerCommon.scala
  common/app/services/repositories.scala
  common/test/common/ModelOrResultTest.scala
Labels: do-not-merge

#25997 Capture all core web vitals
  static/src/javascripts/projects/common/modules/analytics/shouldCaptureMetrics.ts
Labels: bug

#25953 Add Ozone user sync iframe
  static/vendor/data/amp-iframe.html
Labels: commercial, ⚡ AMP

#26001 fix: experiment can only run with extra header
  common/app/experiments/Experiment.scala
Labels: bug

#26009 Stop truncating `sbt` output
  build.sbt
  project/plugins.sbt
Labels: vulnerabilities

#26008 Bump commercial-bundle v1.9.0 + add ab test
  common/app/conf/switches/ABTestSwitches.scala
  package.json
  static/src/javascripts/projects/common/modules/experiments/ab-tests.ts
  static/src/javascripts/projects/common/modules/experiments/tests/eager-prebid.ts
  yarn.lock
Labels: commercial

#26020 Update Ozone user sync URL
  static/vendor/data/amp-iframe.html
Labels: commercial, ⚡ AMP
