Repository guardian/frontend, pull requests merged in 2023-08, with the labels that each got.

#26436 Bump commercial to 10.12.0
  package.json
  yarn.lock
Labels: commercial

#26459 Set the Okta experiment's participation group to Perc1C
  common/app/experiments/Experiments.scala
Labels: Do not merge ⚠️

#26474 Set the Okta participation group to `Perc2A`
  common/app/experiments/Experiments.scala
Labels: Do not merge ⚠️

#26484 Removed unused commercial-features properties
  static/src/javascripts/projects/common/modules/commercial/commercial-features.spec.ts
  static/src/javascripts/projects/common/modules/commercial/commercial-features.ts
Labels: commercial

#26530 Bump commercial to 11.3.0
  package.json
  yarn.lock
Labels: commercial

#26531 fix: scheduler off by default
  common/app/conf/switches/PerformanceSwitches.scala
Labels: bug
