Repository guardian/frontend, pull requests merged in 2023-06, with the labels that each got.

#26178 fix local commercial bundle
  package.json
  webpack.config.dev.js
  webpack.config.js
  webpack.config.prod.js
  yarn.lock
Labels: commercial

#26192 Update contribution epics test parameters
  static/src/javascripts/projects/common/modules/analytics/shouldCaptureMetrics.ts
  static/src/javascripts/projects/common/modules/experiments/tests/remove-business-liveblog-epics.ts
Labels: commercial

#26204 Revert "Downgrade DFP API to test alarm"
  admin/app/dfp/AdUnitAgent.scala
  admin/app/dfp/ApiHelper.scala
  admin/app/dfp/CustomFieldAgent.scala
  admin/app/dfp/CustomTargetingAgent.scala
  admin/app/dfp/DataMapper.scala
  admin/app/dfp/DataValidation.scala
  admin/app/dfp/DfpApi.scala
  admin/app/dfp/PlacementAgent.scala
  admin/app/dfp/Reader.scala
  admin/app/dfp/ServicesWrapper.scala
  admin/app/dfp/SessionLogger.scala
  admin/app/dfp/SessionWrapper.scala
  admin/app/jobs/CommercialDfpReporting.scala
  admin/test/dfp/DfpApiValidationTest.scala
  admin/test/dfp/ReaderTest.scala
  project/Dependencies.scala
Labels: commercial

#26234 Australia state switcher/picker supported in DCR
  facia/app/services/dotcomrendering/FaciaPicker.scala
  facia/test/services/dotcomrendering/FaciaPickerTest.scala
Labels: Fronts :newspaper:

#26245 Remove `dcrJavascriptBundle` Experiment
  common/app/experiments/Experiments.scala
Labels: Health

#26246 Support gradual rollout for Network Fronts based on test percentage
  facia/app/services/dotcomrendering/FaciaPicker.scala
  facia/test/services/dotcomrendering/FaciaPickerTest.scala
Labels: Fronts :newspaper:

#26249 Network fronts are supported
  facia/app/services/dotcomrendering/FaciaPicker.scala
  facia/test/services/dotcomrendering/FaciaPickerTest.scala
Labels: Fronts :newspaper:

#26254 Fix lockfile (Prebid.js)
  yarn.lock
Labels: bug, dependencies
