Repository guardian/frontend, pull requests merged in 2024-08, with the labels that each got.

#27375 Enable correct pressing of highlights container by adding it to fixed/containers
  common/app/layout/slices/FixedContainers.scala
  common/app/layout/slices/Slice.scala
  facia-press/app/frontpress/FapiFrontPress.scala
Labels: fairground

#27381 Remove `updateLogoAdPartner` switch
  common/app/conf/switches/CommercialSwitches.scala
Labels: commercial

#27394 Remove `inline-merchandising`/`im` slot
  admin/app/controllers/admin/CommercialController.scala
  admin/app/dfp/DfpDataCacheJob.scala
  admin/app/dfp/DfpDataExtractor.scala
  admin/app/tools/Store.scala
  admin/app/views/commercial/commercialMenu.scala.html
  admin/app/views/commercial/inlineMerchandisingTargetedTags.scala.html
  admin/conf/routes
  common/app/common/configuration.scala
  common/app/common/dfp/DfpAgent.scala
  common/app/common/dfp/DfpData.scala
  common/app/common/dfp/InlineMerchandiseComponentAgent.scala
  common/app/common/dfp/TagSponsorship.scala
  common/app/dev/DevParametersHttpRequestHandler.scala
  common/app/model/content.scala
  common/app/model/meta.scala
  common/test/common/dfp/InlineMerchandiseComponentAgentTest.scala
  dev-build/conf/routes
  package.json
  static/src/javascripts/types/global.d.ts
  yarn.lock
Labels: commercial

#27417 Bump commercial to v20.5.1
  package.json
  yarn.lock
Labels: commercial

#27428 Bump commercial to 20.6.0
  package.json
  yarn.lock
Labels: commercial

#27429 [Fairground 🎡]  Bump updated header design test to 50 % of users
  common/app/experiments/Experiments.scala
Labels: Do not merge ⚠️

#27441 Bump commercial to 20.6.4
  package.json
  yarn.lock
Labels: commercial
