Repository guardian/frontend, pull requests merged in 2024-02, with the labels that each got.

#26855 Dependencies | Update `identity-auth` and `identity-auth-frontend`
  package.json
  yarn.lock
Labels: dependencies

#26777 Update 01-ab-testing.md: remove Omniture, add BigQuery
  docs/03-dev-howtos/01-ab-testing.md
Labels: Stale

#26885 Bump commercial to 14.4.0
  package.json
  yarn.lock
Labels: commercial

#26905 Bump commercial to 15.1.0
  package.json
  yarn.lock
Labels: commercial

#26908 It’s about time we use “Batter”
  sport/app/cricket/feed/cricketModel.scala
  sport/app/cricket/feed/cricketPaDeserialisation.scala
  sport/app/cricket/views/fragments/cricketFullScorecard.scala.html
Labels: Bug

#26899 Show ads on mobile discussion
  common/app/conf/switches/CommercialSwitches.scala
  package.json
  yarn.lock
Labels: commercial

#26932 Bump commercial to 16.1.0
  package.json
  yarn.lock
Labels: commercial
