Repository guardian/frontend, pull requests merged in 2024-05, with the labels that each got.

#27093 Support the Euro 2024 wall chart
  sport/app/football/controllers/LeagueTableController.scala
  sport/app/football/feed/Competitions.scala
  sport/app/football/model/CompetitionStages.scala
Labels: football

#27083 Bump commercial to 18.0.0
  package.json
  yarn.lock
Labels: commercial

#27099 Bump commercial to v18.1.0
  package.json
  yarn.lock
Labels: commercial

#27125 Fix Onward Journeys experiment
  static/src/javascripts/projects/common/modules/experiments/tests/onward-journeys.ts
Labels: dotcomrendering, Onwards content

#27139 Remove commercial mega test
  common/app/experiments/Experiments.scala
  package.json
  yarn.lock
Labels: commercial

#27155 Bump `browser-sync` to v3
  package.json
  yarn.lock
Labels: dependencies

#27136 Add `0%` server-side test to update logo for Advertising Partner
  common/app/experiments/Experiments.scala
Labels: commercial

#27172 Bump @guardian/commercial to v19.0.0
  package.json
  yarn.lock
Labels: commercial

#27184 Set live updated logo styling for Advertising partner
  common/app/conf/switches/CommercialSwitches.scala
  common/app/experiments/Experiments.scala
Labels: commercial
