Repository guardian/frontend, pull requests merged in 2024-09, with the labels that each got.

#27454 [DO NOT MERGE] [Fairground] Remove updated header test to roll it out to 100%
  common/app/experiments/Experiments.scala
Labels: Do not merge ⚠️, fairground

#27424 Add boostlevel to frontend
  common/app/layout/DisplaySettings.scala
  common/app/model/Formats.scala
  common/app/model/PressedDisplaySettings.scala
  common/test/common/TrailsToShowcaseTest.scala
  common/test/common/facia/FixtureBuilder.scala
  common/test/views/support/TrackingCodeBuilderTest.scala
  project/Dependencies.scala
Labels: fairground

#27475 Limit highlights container to 6 stories
  facia-press/app/frontpress/FapiFrontPress.scala
Labels: fairground

#27492 Bump commercial to v21.0.3
  package.json
  yarn.lock
Labels: commercial

#27489 Remove `surveys` switch
  applications/app/views/fragments/mediaBody.scala.html
  article/app/pages/StoryHtmlPage.scala
  common/app/common/dfp/SurveySponsorshipAgent.scala
  common/app/conf/switches/CommercialSwitches.scala
  common/app/views/main.scala.html
Labels: commercial

#27496 Press 'Best books of 2015' interactive
  common/app/services/dotcomrendering/PressedContent.scala
Labels: Pressed :newspaper:

#27497 Bump facia version to bring in EditionBranding for the Europe edition
  project/Dependencies.scala
Labels: commercial
