Repository guardian/frontend, pull requests merged in 2025-01, with the labels that each got.

#27676 Add audio duration in pressed card
  common/app/model/PressedCard.scala
  common/test/common/TrailsToShowcaseTest.scala
  common/test/common/facia/FixtureBuilder.scala
Labels: fairground

#27700 Add leading zero to podcast duration if needed
  common/app/model/PressedCard.scala
Labels: fairground

#27718 Add aria label for star ratings in email
  facia/app/views/fragments/emailFrontBody.scala.html
Labels: a11y

#27715 Enable ETag-caching & AWS SDK v2 on Facia API requests
  build.sbt
  common/app/common/configuration.scala
  common/app/services/fronts/FrontsApi.scala
  common/app/utils/AWSv2.scala
  project/Dependencies.scala
Labels: AWS SDK v2
