Repository guardian/frontend, pull requests merged in 2025-04, with the labels that each got.

#27791 Identity | Add instructions on developing with okta/sign in local dev
  docs/01-start-here/01-installation-steps.md
  nginx/README.md
Labels: Pending-on-ADMIN-PROD, Pending-on-FRONTS-PROD

#27887 Upgrading Braze SDK from web-sdk-core@3.5.1 to web-sdk@5.8.1
  package.json
  static/src/javascripts/projects/common/modules/commercial/braze/buildBrazeMessaging.ts
  yarn.lock
Labels: Do not merge ⚠️

#27903 Limit scrollable small to 4 stories
  common/app/layout/slices/Slice.scala
  facia-press/app/frontpress/FapiFrontPress.scala
Labels: Pending-on-ADMIN-PROD, Pending-on-FRONTS-PROD

#27904 Bump facia-scala-client to 18.0.1
  project/Dependencies.scala
Labels: Pending-on-ADMIN-PROD, Pending-on-FRONTS-PROD

#27925 Remove GA references that were missed from audit
  common/app/views/support/Commercial.scala
Labels: commercial

#27930 Add AB test for prebid `multibid`
  common/app/conf/switches/ABTestSwitches.scala
Labels: commercial
